---
theme: dark
roots:
  - store: heroic
    path: /home/$USER/.var/app/com.heroicgameslauncher.hgl/config/heroic
backup:
  path: /home/$USER/Games/saves-heroic
restore:
  path: /home/$USER/Games/saves-heroic